name: Generate & push changelog (master only)
on:
  push:
    branches: [master]

jobs:
  generate-push-changelog:
    name: Generate & push changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2.4.2
        with:
          token: ${{ secrets.ALLOWED_GITHUB_TOKEN }}
      - uses: heinrichreimer/github-changelog-generator-action@6f5b9494dd265d6fb7243a10c53dc0169c55f247 # renovate: tag=v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@050a66787244b10a4874a2a5f682130263edc192 # tag=v9.0.0
        with:
          add: CHANGELOG.md
          default_author: github_actions
          message: "Commit last changes to CHANGELOG.md"
